# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pand',
            name='referentienummer',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pand',
            unique_together=set([]),
        ),
    ]
