# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.FileField(default='', upload_to='documenten/', verbose_name='Document')),
            ],
            options={
                'verbose_name_plural': 'Documenten',
            },
        ),
        migrations.CreateModel(
            name='PandDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand')),
                ('pand_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Document')),
            ],
            options={
                'verbose_name_plural': 'Pand Documenten',
            },
        ),
    ]
