# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_document_panddocument'),
    ]

    operations = [
    ]
