# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20160520_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nieuwsbrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Emailadres')),
            ],
            options={
                'verbose_name_plural': 'Contacten Nieuwsbrief',
            },
        ),
    ]
