# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20160615_1745'),
    ]

    operations = [
    ]
