# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_panddocument_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panddocument',
            name='pand',
        ),
        migrations.RemoveField(
            model_name='panddocument',
            name='pand_document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='PandDocument',
        ),
    ]
