# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 16:47
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20160615_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='naam',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/upload/'), upload_to='documenten'),
        ),
    ]
