# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20160615_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='naam',
            field=models.FileField(storage='/upload/', upload_to='documenten'),
        ),
    ]
