# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20160615_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='naam',
            field=models.FileField(upload_to=b'4685a95f-eebd-401a-9efa-257e1e62124d/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='pand',
            name='profiel_foto',
            field=models.FileField(default='', upload_to='', verbose_name='Profiel_foto'),
        ),
    ]
